id: P010559
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-19 20:55:59.032498
source_metadata:
  id: bdr:W3CN521
  title: འདས་ལོག་དཀར་ཆག་བླང་དོར་འབྱེད་པའི་ལྡེ་མིག
  author: ''
  volumes:
    79fd2a4cd1044dd682aff67666ab6a58:
      image_group_id: I3CN8483
      title: ''
      volume_number: 1
      total_pages: 92
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
